const Color = {
    Brown: "#955436",
    Light_Blue: "#AAE0FA",
    Pink: "#D93A96",
    Orange: "#F7941D",
    Red: "#ED1B24",
    Yellow: "#FEF200",
    Green: "#1FB25A",
    Blue: "#0072BB",
}

const TileId = {
    Tile_0: "SAC Loop",
    Tile_1: "Earth and Space Sciences",
    Tile_2: "Community Chest",
    Tile_3: "Javits Lecture Center",
    Tile_4: "Tuition",
    Tile_5: "East Side Dining",
    Tile_6: "Harriman Hall",
    Tile_7: "Chance",
    Tile_8: "Frey Hall",
    Tile_9: "Frank Melville Jr. Memorial Library",
    Tile_10: "Jail",
    Tile_11: "Benedict College",
    Tile_12: "Softheon Bikes",
    Tile_13: "Langmuir College",
    Tile_14: "James College",
    Tile_15: "West Side Dining",
    Tile_16: "Light Engineering",
    Tile_17: "Community Chest",
    Tile_18: "Old Computer Science",
    Tile_19: "New Computer Science",
    Tile_20: "South Parking",
    Tile_21: "Mount College",
    Tile_22: "Chance",
    Tile_23: "Cardozo College",
    Tile_24: "Gershwin College",
    Tile_25: "Roth Cafe",
    Tile_26: "Humanities",
    Tile_27: "Staller Center",
    Tile_28: "SBU Bus",
    Tile_29: "Charles B. Wang Center",
    Tile_30: "Go to Jail",
    Tile_31: "Island Federal Arena",
    Tile_32: "Recreation Center",
    Tile_33: "Community Chest",
    Tile_34: "LaValle Stadium",
    Tile_35: "Jasmine",
    Tile_36: "Chance",
    Tile_37: "Chavez",
    Tile_38: "Student Activity Fee ",
    Tile_39: "Tubman",

}